# Generated by Django 3.0.7 on 2020-06-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury_Yield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bondName', models.CharField(max_length=32)),
                ('couponRate', models.CharField(max_length=32)),
                ('bondPrice', models.CharField(max_length=32)),
                ('bondYield', models.CharField(max_length=32)),
            ],
        ),
    ]
